const constants = {
  c_aqua: 16776960,
  c_black: 0,
  c_blue: 16711680,
  c_dkgray: 4210752,
  c_fuchsia: 16711935,
  c_gray: 8421504,
  c_green: 32768,
  c_lime: 65280,
  c_ltgray: 12632256,
  c_maroon: 128,
  c_navy: 8388608,
  c_olive: 32896,
  c_purple: 8388736,
  c_red: 255,
  c_silver: 12632256,
  c_teal: 8421376,
  c_white: 16777215,
  c_yellow: 65535,
  c_orange: 4235519,

  fa_left: 0,
  fa_center: 1,
  fa_right: 2,
  fa_top: 0,
  fa_middle: 1,
  fa_bottom: 2,

  pr_pointlist: 1,
  pr_linelist: 2,
  pr_linestrip: 3,
  pr_trianglelist: 4,
  pr_trianglestrip: 5,
  pr_trianglefan: 6,

  bm_normal: 0,
  bm_add: 1,
  bm_max: 2,
  bm_subtract: 3,
  bm_zero: 1,
  bm_one: 2,
  bm_src_colour: 3,
  bm_inv_src_colour: 4,
  bm_src_color: 3,
  bm_inv_src_color: 4,
  bm_src_alpha: 5,
  bm_inv_src_alpha: 6,
  bm_dest_alpha: 7,
  bm_inv_dest_alpha: 8,
  bm_dest_colour: 9,
  bm_inv_dest_colour: 10,
  bm_dest_color: 9,
  bm_inv_dest_color: 10,
  bm_src_alpha_sat: 11,
  tf_point: 0,
  tf_linear: 1,
  tf_anisotropic: 2,
  mip_off: 0,
  mip_on: 1,
  mip_markedonly: 2,
  cmpfunc_never: 1,
  cmpfunc_less: 2,
  cmpfunc_equal: 3,
  cmpfunc_lessequal: 4,
  cmpfunc_greater: 5,
  cmpfunc_notequal: 6,
  cmpfunc_greaterequal: 7,
  cmpfunc_always: 8,
  cull_noculling: 0,
  cull_clockwise: 1,
  cull_counterclockwise: 2,
  lighttype_dir: 0,
  lighttype_point: 1,

  AG_CATEGORY: 0,
  AG_SPRITE: 1,
  AG_AIR_SPRITE: 13,
  AG_HURTBOX_SPRITE: 16,
  AG_HURTBOX_AIR_SPRITE: 19,
  AG_NUM_WINDOWS: 4,
  AG_HAS_LANDING_LAG: 7,
  AG_OFF_LEDGE: 8,
  AG_LANDING_LAG: 12,
  AG_STRONG_CHARGE_WINDOW: 10,
  AG_USES_CUSTOM_GRAVITY: 24,
  AG_WINDOW_TYPE: 1,
  AG_WINDOW_LENGTH: 2,
  AG_WINDOW_ANIM_FRAMES: 3,
  AG_WINDOW_ANIM_FRAME_START: 4,
  AG_WINDOW_HSPEED: 5,
  AG_WINDOW_VSPEED: 6,
  AG_WINDOW_HSPEED_TYPE: 7,
  AG_WINDOW_VSPEED_TYPE: 8,
  AG_WINDOW_HAS_CUSTOM_FRICTION: 9,
  AG_WINDOW_CUSTOM_AIR_FRICTION: 10,
  AG_WINDOW_CUSTOM_GROUND_FRICTION: 11,
  AG_WINDOW_CUSTOM_GRAVITY: 26,
  AG_WINDOW_HAS_WHIFFLAG: 12,
  AG_WINDOW_INVINCIBILITY: 13,
  AG_WINDOW_HITPAUSE_FRAME: 24,
  AG_WINDOW_CANCEL_TYPE: 31,
  AG_WINDOW_CANCEL_FRAME: 32,
  AG_WINDOW_HAS_SFX: 57,
  AG_WINDOW_SFX: 58,
  AG_WINDOW_SFX_FRAME: 59,
  HG_PARENT_HITBOX: 0,
  HG_HITBOX_TYPE: 1,
  HG_WINDOW: 2,
  HG_WINDOW_CREATION_FRAME: 3,
  HG_LIFETIME: 4,
  HG_HITBOX_X: 5,
  HG_HITBOX_Y: 6,
  HG_WIDTH: 7,
  HG_HEIGHT: 8,
  HG_SHAPE: 9,
  HG_PRIORITY: 10,
  HG_DAMAGE: 11,
  HG_ANGLE: 12,
  HG_BASE_KNOCKBACK: 13,
  HG_KNOCKBACK_SCALING: 14,
  HG_EFFECT: 15,
  HG_BASE_HITPAUSE: 16,
  HG_HITPAUSE_SCALING: 17,
  HG_VISUAL_EFFECT: 18,
  HG_VISUAL_EFFECT_X_OFFSET: 19,
  HG_VISUAL_EFFECT_Y_OFFSET: 20,
  HG_HIT_SFX: 21,
  HG_ANGLE_FLIPPER: 22,
  HG_EXTRA_HITPAUSE: 23,
  HG_GROUNDEDNESS: 24,
  HG_EXTRA_CAMERA_SHAKE: 25,
  HG_IGNORES_PROJECTILES: 26,
  HG_HIT_LOCKOUT: 27,
  HG_EXTENDED_PARRY_STUN: 28,
  HG_HITBOX_GROUP: 29,
  HG_HITSTUN_MULTIPLIER: 30,
  HG_DRIFT_MULTIPLIER: 31,
  HG_SDI_MULTIPLIER: 32,
  HG_TECHABLE: 33,
  HG_FORCE_FLINCH: 34,
  HG_FINAL_BASE_KNOCKBACK: 35,
  HG_THROWS_ROCK: 36,
  HG_PROJECTILE_SPRITE: 37,
  HG_PROJECTILE_MASK: 38,
  HG_PROJECTILE_ANIM_SPEED: 39,
  HG_PROJECTILE_UNBASHABLE: 40,
  HG_PROJECTILE_HSPEED: 42,
  HG_PROJECTILE_VSPEED: 43,
  HG_PROJECTILE_GRAVITY: 44,
  HG_PROJECTILE_GROUND_FRICTION: 45,
  HG_PROJECTILE_AIR_FRICTION: 46,
  HG_PROJECTILE_WALL_BEHAVIOR: 47,
  HG_PROJECTILE_GROUND_BEHAVIOR: 48,
  HG_PROJECTILE_ENEMY_BEHAVIOR: 49,
  HG_PROJECTILE_LIFESPAN: 50,
  HG_PROJECTILE_PARRY_STUN: 51,
  HG_PROJECTILE_DOES_NOT_REFLECT: 52,
  HG_PROJECTILE_IS_TRANSCENDENT: 53,
  HG_PROJECTILE_DESTROY_EFFECT: 54,
  PS_IDLE: 24,
  PS_IDLE_AIR: 1,
  PS_CROUCH: 32,
  PS_JUMPSQUAT: 28,
  PS_FIRST_JUMP: 3,
  PS_DOUBLE_JUMP: 2,
  PS_WALL_JUMP: 16,
  PS_LAND: 13,
  PS_WALK: 26,
  PS_WALK_TURN: 20,
  PS_DASH_START: 22,
  PS_DASH: 23,
  PS_DASH_STOP: 27,
  PS_DASH_TURN: 29,
  PS_WAVELAND: 21,
  PS_ATTACK_AIR: 5,
  PS_ATTACK_GROUND: 6,
  PS_LANDING_LAG: 19,
  PS_HITSTUN: 12,
  PS_HITSTUN_LAND: 7,
  PS_TUMBLE: 0,
  PS_PRATFALL: 10,
  PS_PRATLAND: 11,
  PS_AIR_DODGE: 8,
  PS_PARRY_START: 30,
  PS_PARRY: 9,
  PS_ROLL_BACKWARD: 33,
  PS_ROLL_FORWARD: 34,
  PS_TECH_GROUND: 31,
  PS_TECH_BACKWARD: 35,
  PS_TECH_FORWARD: 36,
  PS_WALL_TECH: 18,
  PS_SPAWN: 25,
  PS_RESPAWN: 14,
  PS_DEAD: 15,
  PS_WRAPPED: 37,
  PS_FROZEN: 38,
  SC_HITSTUN: 4,
  SC_GROUND_NEUTRAL: 40,
  SC_GROUND_COMMITTED: 42,
  SC_AIR_NEUTRAL: 41,
  SC_AIR_COMMITTED: 43,
  AT_JAB: 1,
  AT_FTILT: 4,
  AT_DTILT: 5,
  AT_UTILT: 6,
  AT_FSTRONG: 7,
  AT_DSTRONG: 8,
  AT_USTRONG: 9,
  AT_DATTACK: 10,
  AT_FAIR: 11,
  AT_BAIR: 12,
  AT_DAIR: 13,
  AT_UAIR: 14,
  AT_NAIR: 15,
  AT_FSPECIAL: 16,
  AT_DSPECIAL: 17,
  AT_USPECIAL: 18,
  AT_NSPECIAL: 19,
  AT_TAUNT: 35,
  AT_FSTRONG_2: 20,
  AT_DSTRONG_2: 21,
  AT_USTRONG_2: 22,
  AT_FTHROW: 26,
  AT_UTHROW: 27,
  AT_DTHROW: 28,
  AT_NTHROW: 29,
  AT_NSPECIAL_AIR: 41,
  AT_NSPECIAL_2: 33,
  AT_FSPECIAL_AIR: 34,
  AT_FSPECIAL_2: 25,
  AT_USPECIAL_GROUND: 23,
  AT_USPECIAL_2: 24,
  AT_DSPECIAL_AIR: 32,
  AT_DSPECIAL_2: 30,
  AT_TAUNT_2: 36,
  AT_EXTRA_1: 31,
  AT_EXTRA_2: 37,
  AT_EXTRA_3: 38,
  VICTORY_THEME_ZETTERBURN: 2,
  VICTORY_THEME_ORCANE: 3,
  VICTORY_THEME_WRASTOR: 4,
  VICTORY_THEME_KRAGG: 5,
  VICTORY_THEME_FORSBURN: 6,
  VICTORY_THEME_MAYPUL: 7,
  VICTORY_THEME_ABSA: 8,
  VICTORY_THEME_ETALUS: 9,
  VICTORY_THEME_ORI: 10,
  VICTORY_THEME_RANNO: 11,
  VICTORY_THEME_CLAIREN: 12,
  VICTORY_THEME_SYLVANOS: 13,
  VICTORY_THEME_ELLIANA: 14,
  VICTORY_THEME_SHOVEL_KNIGHT: 15,
  SD_X_POS: 0,
  SD_Y_POS: 1,
  SD_TOP_BLASTZONE: 2,
  SD_BOTTOM_BLASTZONE: 3,
  SD_SIDE_BLASTZONE: 4,
  SD_WIDTH: 5,
}

export default constants;
export const reverseLookup = (prefix, value) => {
  for (const [key, v] of Object.entries(value)) {
    if (v === value && key.startsWith(prefix)) return key;
  }
  return null;
}

export const baseAttack = {
  AG_CATEGORY: 0,
  AG_SPRITE: 0,
  AG_AIR_SPRITE: 0,
  AG_HURTBOX_SPRITE: 0,
  AG_HURTBOX_AIR_SPRITE: 0,
  AG_NUM_WINDOWS: 0,
  AG_HAS_LANDING_LAG: 0,
  AG_OFF_LEDGE: 0,
  AG_LANDING_LAG: 0,
  AG_STRONG_CHARGE_WINDOW: 0,
  AG_USES_CUSTOM_GRAVITY: 0
}

export const baseWindow = {
  AG_WINDOW_TYPE: 0,
  AG_WINDOW_LENGTH: 0,
  AG_WINDOW_ANIM_FRAMES: 0,
  AG_WINDOW_ANIM_FRAME_START: 0,
  AG_WINDOW_HSPEED: 0,
  AG_WINDOW_VSPEED: 0,
  AG_WINDOW_HSPEED_TYPE: 0,
  AG_WINDOW_VSPEED_TYPE: 0,
  AG_WINDOW_HAS_CUSTOM_FRICTION: 0,
  AG_WINDOW_CUSTOM_AIR_FRICTION: 0,
  AG_WINDOW_CUSTOM_GROUND_FRICTION: 0,
  AG_WINDOW_CUSTOM_GRAVITY: 0,
  AG_WINDOW_HAS_WHIFFLAG: 0,
  AG_WINDOW_INVINCIBILITY: 0,
  AG_WINDOW_HITPAUSE_FRAME: 0,
  AG_WINDOW_CANCEL_TYPE: 0,
  AG_WINDOW_CANCEL_FRAME: 0,
  AG_WINDOW_HAS_SFX: 0,
  AG_WINDOW_SFX: 0,
  AG_WINDOW_SFX_FRAME: 0,
}

export const baseHitbox = {
  HG_PARENT_HITBOX: 0,
  HG_HITBOX_TYPE: 0,
  HG_WINDOW: 0,
  HG_WINDOW_CREATION_FRAME: 0,
  HG_LIFETIME: 0,
  HG_HITBOX_X: 0,
  HG_HITBOX_Y: 0,
  HG_WIDTH: 0,
  HG_HEIGHT: 0,
  HG_SHAPE: 0,
  HG_PRIORITY: 0,
  HG_DAMAGE: 0,
  HG_ANGLE: 0,
  HG_BASE_KNOCKBACK: 0,
  HG_KNOCKBACK_SCALING: 0,
  HG_EFFECT: 0,
  HG_BASE_HITPAUSE: 0,
  HG_HITPAUSE_SCALING: 0,
  HG_VISUAL_EFFECT: 0,
  HG_VISUAL_EFFECT_X_OFFSET: 0,
  HG_VISUAL_EFFECT_Y_OFFSET: 0,
  HG_HIT_SFX: 0,
  HG_ANGLE_FLIPPER: 0,
  HG_EXTRA_HITPAUSE: 0,
  HG_GROUNDEDNESS: 0,
  HG_EXTRA_CAMERA_SHAKE: 0,
  HG_IGNORES_PROJECTILES: 0,
  HG_HIT_LOCKOUT: 0,
  HG_EXTENDED_PARRY_STUN: 0,
  HG_HITBOX_GROUP: 0,
  HG_HITSTUN_MULTIPLIER: 0,
  HG_DRIFT_MULTIPLIER: 0,
  HG_SDI_MULTIPLIER: 0,
  HG_TECHABLE: 0,
  HG_FORCE_FLINCH: 0,
  HG_FINAL_BASE_KNOCKBACK: 0,
  HG_THROWS_ROCK: 0,
  HG_PROJECTILE_SPRITE: 0,
  HG_PROJECTILE_MASK: 0,
  HG_PROJECTILE_ANIM_SPEED: 0,
  HG_PROJECTILE_UNBASHABLE: 0,
  HG_PROJECTILE_HSPEED: 0,
  HG_PROJECTILE_VSPEED: 0,
  HG_PROJECTILE_GRAVITY: 0,
  HG_PROJECTILE_GROUND_FRICTION: 0,
  HG_PROJECTILE_AIR_FRICTION: 0,
  HG_PROJECTILE_WALL_BEHAVIOR: 0,
  HG_PROJECTILE_GROUND_BEHAVIOR: 0,
  HG_PROJECTILE_ENEMY_BEHAVIOR: 0,
  HG_PROJECTILE_LIFESPAN: 0,
  HG_PROJECTILE_PARRY_STUN: 0,
  HG_PROJECTILE_DOES_NOT_REFLECT: 0,
  HG_PROJECTILE_IS_TRANSCENDENT: 0,
  HG_PROJECTILE_DESTROY_EFFECT: 0
}

export const animationNames = [
  "idle",
  "walk",
  "walkturn",
  "jump",
  "jumpstart",
  "walljump",
  "doublejump",
  "airdodoge",
  "airdodoge_forward",
  "airdodoge_back",
  "airdodoge_up",
  "airdodoge_upforward",
  "airdodoge_upback",
  "airdodoge_down",
  "airdodoge_downforward",
  "airdodoge_downback",
  "plat",
  "dash",
  "dashstart",
  "dashstop",
  "dashturn",
  "land",
  "landinglag",
  "waveland",
  "pratfall",
  "crouch",
  "tech",
  "roll_forward",
  "roll_backward",
  "parry",
  "hurt",
  "bighurt",
  "hurtground",
  "bouncehurt",
  "spinhurt",
  "uphurt",
  "downhurt"
]

export const inputList = [
  'attack',
  'special',
  'jump',
  'shield',
  'strong',
  'taunt',
  'up',
  'down',
  'left',
  'right',
  'up_strong',
  'down_strong',
  'left_strong',
  'right_strong',
  'up_stick',
  'down_stick',
  'left_stick',
  'right_stick'
]

export const SC_HITSTUN_states = [
  'PS_HITSTUN',
  'PS_HITSTUN_LAND',
  'PS_WRAPPED',
  'PS_FROZEN',
]

export const SC_AIR_NEUTRAL_states = [
  'PS_IDLE_AIR',
  'PS_FIRST_JUMP',
  'PS_DOUBLE_JUMP',
  'PS_TUMBLE',
]

export const SC_AIR_COMMITTED_states = [
  'PS_WALL_JUMP',
  'PS_ATTACK_AIR',
  'PS_PRATFALL',
  'PS_AIR_DODGE',
  'PS_WALL_TECH',
  'PS_RESPAWN',
  'PS_DEAD',
]

export const SC_GROUND_NEUTRAL_states = [
  'PS_IDLE',
  'PS_CROUCH',
  'PS_WALK',
]

export const SC_GROUND_COMMITTED_states = [
  'PS_LAND',
  'PS_SPAWN',
  'PS_PRATLAND',
  'PS_LANDING_LAG',
  'PS_WALK_TURN',
  'PS_ATTACK_GROUND',
  'PS_WAVELAND',
  'PS_DASH_START',
  'PS_DASH',
  'PS_DASH_TURN',
  'PS_DASH_STOP',
  'PS_PARRY_START',
  'PS_PARRY',
  'PS_TECH_GROUND',
  'PS_TECH_BACKWARD',
  'PS_TECH_FORWARD',
  'PS_ROLL_BACKWARD',
  'PS_ROLL_FORWARD',
  'PS_JUMPSQUAT',
]

export const defaultInstanceVariables = {
  id: 0,
  visible: true,
  solid: true,
  persistent: true,
  depth: 0,
  layer: 0,
  alarm: 0,
  object_index: 0,

  sprite_index: 0,
  sprite_width: 0,
  sprite_height: 0,
  sprite_xoffset: 0,
  sprite_yoffset: 0,
  image_alpha: 1,
  image_blend: 0,
  image_index: 0,
  image_number: 0,
  image_speed: 1,
  image_xscale: 1,
  image_yscale: 1,

  mask_index: 0,
  bbox_bottom: 0,
  bbox_left: 0,
  bbox_right: 0,
  bbox_top: 0,

  direction: 0,
  friction: 0,
  gravity: 0,
  gravity_direction: 0,
  hspeed: 0,
  vspeed: 0,
  speed: 0,
  xstart: 0,
  ystart: 0,
  x: 1000,
  y: 1000,
  xprevious: 0,
  yprevious: 0,

  path_index: 0,
  path_position: 0,
  path_positionprevious: 0,
  path_speed: 0,
  path_scale: 0,
  path_orientation: 0,
  path_endaction: 0,

  timeline_index: 0,
  timeline_running: 0,
  timeline_speed: 0,
  timeline_position: 0,
  timeline_loop: 0,

  // just gonna not cover physics unless absolutely necessary lmao
}

export const baseVars = {
  'sprite_index': 'idle',
  'url': 0,
  'player': 0,
  'state': null,
  'state_timer': -1,
  'state_cat': null,
  'prev_state': null,
  'attack': 0,
  'window': 0,
  'window_timer': 0,
  'spr_dir': 0,
  'spr_angle': 0,
  'free': 0,
  'hsp': 0,
  'vsp': 0,
  'joy_pad_idle': 0,
  'joy_dir': 0,

  ...(() => {
    let out = {};
    for (const name of inputList) {
      out[name + '_pressed'] = 0;
      out[name + '_hard_pressed'] = 0;
      out[name + '_down'] = 0;
    }
    return out;
  })(),

  'was_parried': 0,
  'can_move': 0,
  'can_jump': 0,
  'can_attack': 0,
  'can_strong': 0,
  'can_ustrong': 0,
  'can_special': 0,
  'can_shield': 0,
  'can_wall_jump': 0,
  'has_walljump': 0,
  'has_airdodge': 0,
  'can_fast_fall': 0,
  'djumps': 0,
  'max_djumps': 0,
  'off_edge': 0,
  'super_armor': 0,
  'soft_armor': 0,
  'invincible': 0,
  'invince_time': 0,
  'hitpause': 0,
  'hitstop': 0,
  'hitstop_full': 0,
  'has_hit': 0,
  'has_hit_player': 0,
  'can_wall_cling': 0,
  'clinging': 0,
  'grav': 0,
  'strong_charge': 0,

  'move_cooldownattack': 0,

  'hit_player_obj': 0,
  'last_attack': 0,
  'last_hbox_num': 0,
  'old_hsp': 0,
  'old_vsp': 0,
  'marked': 0,
  'wrapped': 0,
  'wrapped_player': 0,
  'burned': 0,
  'burnt_id': 0,
  'burn_timer': 0,
  'bubbled': 0,
  'bubbled_id': 0,
  'bubble_time': 0,
  'poison': 0,
  'stuck': 0,
  'stuck_id': 0,
  'clone': 0,
  'clones_player_id': 0,
  'draw_indicator': 0,
  'old_jump': 0,
  'outline_color': 0,

  'hurtbox_spr': 0,
  'crouchbox_spr': 0,
  'air_hurtbox_spr': 0,
  'hitstun_hurtbox_spr': 0,
  'knockback_adj': 0,
  'walk_speed': 0,
  'walk_accel': 0,
  'walk_turn_time': 0,
  'initial_dash_time': 0,
  'initial_dash_speed': 0,
  'dash_speed': 0,
  'dash_turn_time': 0,
  'dash_turn_accel': 0,
  'dash_stop_time': 0,
  'dash_stop_percent': 0,
  'ground_friction': 0,
  'moonwalk_accel': 0,
  'max_djumps': 0,
  'jump_start_time': 0,
  'jump_speed': 0,
  'short_hop_speed': 0,
  'djump_speed': 0,
  'jump_change': 0,
  'djump_accel': 0,
  'djump_accel_start_time': 0,
  'djump_accel_end_time': 0,
  'leave_ground_max': 0,
  'air_max_speed': 0,
  'max_jump_hsp': 0,
  'air_accel': 0,
  'air_friction': 0,
  'double_jump_time': 0,
  'gravity_speed': 0,
  'hitstun_grav': 0,
  'max_fall': 0,
  'fast_fall': 0,
  'land_time': 0,
  'prat_land_time': 0,
  'prat_fall_accel': 0,
  'walljump_hsp': 0,
  'walljump_vsp': 0,
  'walljump_time': 0,
  'roll_forward_max': 0,
  'roll_backward_max': 0,
  'wave_land_time': 0,
  'wave_land_adj': 0,
  'wave_friction': 0,
  'techroll_speed': 0,
  'air_dodge_speed': 0,
  'char_height': 0,
  'bubble_x': 0,
  'bubble_y': 0,

  'wall_frames': 0,
  'dodge_startup_frames': 0,
  'dodge_active_frames': 0,
  'dodge_recovery_frames': 0,
  'tech_active_frames': 0,
  'tech_recovery_frames': 0,
  'techroll_startup_frames': 0,
  'techroll_active_frames': 0,
  'techroll_recovery_frames': 0,
  'air_dodge_startup_frames': 0,
  'air_dodge_active_frames': 0,
  'air_dodge_recovery_frames': 0,
  'roll_forward_startup_frames': 0,
  'roll_forward_active_frames': 0,
  'roll_forward_recovery_frames': 0,
  'roll_back_startup_frames': 0,
  'roll_back_active_frames': 0,
  'roll_back_recovery_frames': 0,
  'idle_anim_speed': 0,
  'walk_anim_speed': 0,
  'dash_anim_speed': 0,
  'pratfall_anim_speed': 0,

  'land_sound': 0,
  'waveland_sound': 0,
  'jump_sound': 0,
  'djump_sound': 0,
  'air_dodge_sound': 0,
  'landing_lag_sound': 0,

  ...defaultInstanceVariables
}